### ISSUE TITLE
`add` method called on `String` instead of `Iri` object causes `/responses`, `/plans`, and `/tasks` pages to crash with `NoMethodError`

### ISSUE THREAD

**Issue by morphqdd** [yegor256/0rsk#488]
**What happens**

Three Haml templates have a misplaced closing parenthesis, so `.add(...)` is called on the string literal instead of on the `Iri` object:

- `views/responses.haml:9` - `title: 'New risk triple'.add(id: triple[:id])`
- `views/plans.haml:46` - `title: 'View responses'.add(id: r[:triple])`
- `views/tasks.haml:46` - `title: 'View responses'.add(id: t[:triple])`

`String` has no `add` method, so rendering raises:

```
NoMethodError: undefined method 'add' for an instance of String
```

`/responses?id=N` has that line at the top of the template, outside any loop, so it fails on every request. That is the page `/triple/save` redirects to, so saving a triple ends on an error page. `/plans` and `/tasks` fail as soon as the account has at least one row, because the broken line sits inside the `plans.each` and `tasks.each` loops.

The `href` is broken too. It is built as `iri.cut('/responses')` with no `id`, so even without the exception the link would point to `/responses` without a triple id, and `Integer(params[:id])` there would raise.

Reproduced by rendering the exact attribute line:

```ruby
require 'haml'
require 'iri'
tpl = "%a{href: Iri.new('http://x/responses'), title: 'View responses'.add(id: 42)}<\n  hello\n"
Haml::Template.new(format: :xhtml) { tpl }.render(Object.new)
# NoMethodError: undefined method 'add' for an instance of String
```

The tests do not catch it. `test_user_pages` logs in as `bill` against an empty database, so `plans.each` and `tasks.each` never iterate, and `/responses` is not requested by any test.

Introduced in fbf3d6b (`#12: add title HTML attributes to all links`, #331).

**What should happen**

The `add` call belongs on the `Iri`, not on the title text, for example:

```haml
%a{href: iri.cut('/responses').add(id: t[:triple]), title: 'View responses'}<
```

All three pages should render, and the link should carry the triple id.

**Comment by 0crat** [comment]
@morphqdd Thanks for reporting a new bug! You've earned +18 points. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that [doesn't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) as good as you might expect, [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Your running score is [+5968](https://zerocracy.github.io/judges-action/zerocracy-vitals.html); don't forget to check your [Zerocracy account](https://www.zerocracy.com/) too).
